- name: Backend Setup
  hosts: all
  become: true
  tasks:

    - name: Disable default version of NodeJS
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: Enable NodeJS18 version
      ansible.builtin.shell: dnf module enable nodejs:18 -y

    - name: Install the new NodeJS default version (which is version 18)
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: Configure backend
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Adding application user
      ansible.builtin.user:
        name: expense

    - name: Remove existing App Content
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create Application Directory
      ansible.builtin.file:
       path: /app
       state: directory

    - name: Download & Extract Application content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
        remote_src: true

    - name: Download Dependencies
      community.general.npm:
        path: /app

    - name: Reloading Systemd and Start Backend service
      ansible.builtin.systemd_service:
        name: backend
        state: restarted
        enabled: yes

    - name: Install Mysql Client
      ansible.builtin.dnf:
        name: mysql
        state: installed

# The load schema task will throw an error if we don't install it because
# the module mysql_db is not an Ansible module, it comes from the community.mysql collection version 3.8.0
# This collection might comes with ansible but it is not included in ansible-core.
# Either way to use this module there is further requirements.
#
    - name: Install Python library for Mysql module in ansible (python3-PyMySQL.noarch)
      ansible.builtin.dnf:
        name: python3-PyMySQL
        state: installed

    - name: Load Schema
      community.mysql.mysql_db:
        name: all
        target: /app/schema/backend.sql
        login_user: root
        login_password: ExpenseApp@1
        login_host: 172.31.43.148


